[config]
schemaVersion = "0.0.1"

[package]
namespace = "loaforc"
name = "loaforcsSoundAPI_LethalCompany"
description = "LethalCompany bindings for loaforcsSoundAPI (v2)"
websiteUrl = ""
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
loaforc-loaforcsSoundAPI_Beta = "2.0.0"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "../../Packages"

[[build.copy]]
source = "../bin/Release/netstandard2.1/me.loaforc.soundapi.lethalcompany.dll"
target = "BepInEx/plugins/loaforcsSoundAPI_LethalCompany/"

[publish]
repository = "https://thunderstore.io"
communities = [ "riskofrain2", ]
[publish.categories]
riskofrain2 = [ "items", "skills", ]